resources:
  pipelines:
    pipeline_demopipeline:
      name: demopipeline
      libraries:
        - glob:
            include: ../../src/pipeline/demopipeline/transformations/**
      schema: default
      continuous: false
      development: false
      photon: true
      channel: CURRENT
      catalog: workspace
      serverless: true
      root_path: ../../src/pipeline/demopipeline